#!/bin/sh

# TimeZone
echo "Setting timezone to ${TZ}..."
ln -snf /usr/share/zoneinfo/"${TZ}" /etc/localtime
echo "${TZ}" >/etc/timezone

# httpd
MMONIT_USERNAME=${MMONIT_USERNAME:-admin}
MMONIT_PASSWORD=${MMONIT_PASSWORD:-changeme}

if [ ! -f /etc/monit/config/httpd.cfg ]; then
	touch /etc/monit/config/httpd.cfg
	cat <<EOF >>/etc/monit/config/httpd.cfg
# Generated by entrypoint.sh
set httpd
    port ${MONIT_PORT}
    allow localhost
    allow "::1"
    allow ${NETWORK}/${NETMASK}
    allow ${MMONIT_USERNAME}:${MMONIT_PASSWORD}
EOF
fi

# M/Monit connection string
if [ ! -f /etc/monit/config/mmonit.cfg ]; then
	touch /etc/monit/config/mmonit.cfg
	cat <<EOF >>/etc/monit/config/mmonit.cfg
# Generated by entrypoint.sh
set monit ${MMONIT_URL}
EOF
fi

echo "Launch monit..."
exec "$@"
